In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy.linalg import inv

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/cyberlab/linear_train.csv')
test = pd.read_csv('/content/drive/MyDrive/cyberlab/linear_test_data.csv')

In [ ]:
test

ids           A           B          C         D          E  \
0      96396  146.790641  223.711806  -0.881371 -0.322721  -6.017133   
1      80166   33.253653  285.935229  -3.352611  0.207565  27.865333   
2      20516  180.531799  208.420343   9.846188  0.056100 -58.428496   
3      88881 -306.361163  255.513561 -11.604514  0.047190 -33.017575   
4      69115  447.724328  260.956969   4.783504  0.125163  -5.139915   
...      ...         ...         ...        ...       ...        ...   
19995  59011 -426.468515  291.551614  26.300724  0.130730  -4.872083   
19996  66308  -19.681262  202.621592  31.471703 -0.078818 -41.499470   
19997  99637 -208.062150  218.788471  -9.157649  0.030381  -0.065924   
19998  84616  246.772616  229.348154  54.293518  0.232136  43.199142   
19999  66210  151.898254  261.236986 -85.466935  0.181286  37.720083   

               F           G          H           I  ...           K  \
0      47.178031   35.602711  -8.933317   95.386076  ...  181.354189   
1      14.509716   39.281848  -4.864431 -595.380114  ...  145.700293   
2      30.214517   66.251581  31.523355 -443.783229  ...  106.941506   
3      46.154984   32.370151  -6.535854  -85.814496  ...  145.675074   
4      28.094844   93.076054   2.500579 -643.852271  ...  127.333215   
...          ...         ...        ...         ...  ...         ...   
19995  17.399959   70.618502  -4.460998 -694.240375  ...  136.767406   
19996   9.881198   54.743271  14.100738  -74.854393  ...  153.252547   
19997  35.895902  105.127438 -84.720301 -453.066178  ...  169.877357   
19998   6.230007   89.287017   2.239845  167.285540  ...  152.720487   
19999  44.421450   73.145185 -11.386356   -2.561581  ...  105.839687   

               L          M            N            O          P           Q  \
0      -7.966671  46.040472   661.719092 -1952.914045  -5.495444  815.628857   
1      31.679372  74.035799   479.886479 -1962.005676  32.900208  752.489552   
2      40.339842  -1.463878 -1192.020689 -2045.601034  78.949252  762.424938   
3     -31.362047 -18.208619   693.586581 -1951.320671   5.432544  773.038782   
4     -19.122905  20.257857   -57.491322 -1988.874566 -14.716299  761.557824   
...          ...        ...          ...          ...        ...         ...   
19995  16.565619  -2.386540   -44.753140 -1988.237657 -41.936271  817.753509   
19996 -10.708559 -50.903469   260.286893 -1972.985655 -13.514805  801.203063   
19997  -5.008809  19.220771   488.152892 -1961.592355  21.889645  802.930133   
19998  -3.644455 -34.817907  -772.011286 -2024.600564  14.743530  779.334314   
19999  -0.466380  15.630515   198.260618 -1976.086969 -35.193154  735.736773   

               R           S           T  
0       4.880546  125.785551  800.204772  
1      30.748264  130.832421  736.119143  
2     -44.226575    7.939280  833.656738  
3     -38.283247  156.536709  768.081726  
4      27.932361 -236.948302  791.210566  
...          ...         ...         ...  
19995  41.442877  272.775392  765.619881  
19996  29.506691  -38.517142  823.359433  
19997  -5.941360  -67.821223  811.022376  
19998  67.348858  363.347336  748.942688  
19999   8.999451  -22.703220  790.467071  

[20000 rows x 21 columns]

In [ ]:
df.drop(labels = 'Unnamed: 0' , axis = 1).head(5)

A           B          C         D          E          F  \
0 -284.685568  284.567363  18.462706  0.012380 -52.394580  -0.942413   
1 -428.480005  307.240676  22.632897 -0.099657   6.294685  30.440746   
2  -25.800879  237.433758  -0.467505 -0.115813  -7.837079  21.598922   
3 -292.645787  249.444200  -3.661449  0.020113  -4.273514  21.421400   
4 -264.114362  259.031693 -17.772049 -0.108774   6.512923  13.657296   

            G          H           I            J  ...          L          M  \
0    6.746190  19.595626  554.989342  1560.150744  ...  33.451992  -9.171214   
1   95.919775 -52.450992 -872.531179  1544.933514  ...  14.848331 -33.556867   
2  158.095089   2.554397  136.298244  1550.705661  ... -12.662449  28.956309   
3   71.012817  49.089192 -444.041731  1585.456001  ...  -1.741291 -65.225030   
4   78.446286  20.942401 -257.340694  1553.952288  ...  17.309833  17.309769   

             N            O          P           Q          R           S  \
0   528.122484 -1959.593876 -47.348529  767.129260 -12.001084   83.978055   
1  -569.261772 -2014.463089  20.042132  769.298704  18.057370  -55.521630   
2  1069.504591 -1932.524770  18.419684  781.523541  70.652625  302.121708   
3   -35.017662 -1987.750883  32.222111  774.167118 -38.784611 -171.210149   
4 -1086.046476 -2040.302324  22.900939  809.692581 -32.675473  104.996827   

            T       label  
0  737.317448 -218.016231  
1  775.407458  154.140849  
2  810.402101  394.849701  
3  793.225247  -83.932183  
4  841.923375 -120.640357  

[5 rows x 21 columns]

In [ ]:
y = (df['label'].to_numpy())
y[:5]

array([-218.01623149,  154.14084898,  394.84970115,  -83.93218298,
       -120.6403571 ])

# Linear regression FINAL CODE

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy.linalg import inv

df = pd.read_csv('/content/drive/MyDrive/cyberlab/linear_train.csv')
test = pd.read_csv('/content/drive/MyDrive/cyberlab/linear_test_data.csv')

features = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T']

x_test = test[features].to_numpy()
ids = test[["ids"]].values
ids = ids.reshape(ids.shape[0], 1)

df.drop(labels = 'Unnamed: 0' , axis = 1)

y = (df['label'].to_numpy())

x = df[features]
def bias(X):
    ones = np.ones(X.shape[0]).reshape(X.shape[0], 1)
    #global x
    x = (np.concatenate((ones, X), 1))
    return x

def normalize(X):
    mu = X.mean(0)
    std = X.std(0)
    return (X - mu) / std, mu, std

def n_eq(X, y):
    return inv(X.T.dot(X)).dot(X.T).dot(y)

def predict(parameters,x):
    res = []
    for i in range(x.shape[0]):
      res.append(np.dot(x[i, :], parameters))

    #res = np.array(res)

    return res

def accuracy(y,yhat):
  d1 = y - yhat
  d2 = y - y.mean()
  r2 = 1 - d1.dot(d1) / d2.dot(d2)
  return r2



#x, mu, std = normalize(x)
x = bias(x)
parameters = n_eq(x, y)
#res = predict(parameters, x)
#print("Accuracy: ", accuracy(y , res) * 100 , "%")

#x_test, m, s = normalize(x_test)
x_test = bias(x_test)
res = predict(parameters, x_test)
res = np.array(res)
res = res.reshape(res.shape[0], 1)
output = np.concatenate((ids, res), 1)

res1 = res.T[0]
ids1 = ids.T[0]

outputDict = {
    'Ids': list(ids1),
    'Result': list(res1)
}

outputDictdf = pd.DataFrame(outputDict)

outputDictdf.to_csv("LinearRegressionOutputPandas.csv")

In [ ]:
np.savetxt('linearOutput.csv', output, delimiter= ',')

In [ ]:
test

ids           A           B          C         D          E  \
0      96396  146.790641  223.711806  -0.881371 -0.322721  -6.017133   
1      80166   33.253653  285.935229  -3.352611  0.207565  27.865333   
2      20516  180.531799  208.420343   9.846188  0.056100 -58.428496   
3      88881 -306.361163  255.513561 -11.604514  0.047190 -33.017575   
4      69115  447.724328  260.956969   4.783504  0.125163  -5.139915   
...      ...         ...         ...        ...       ...        ...   
19995  59011 -426.468515  291.551614  26.300724  0.130730  -4.872083   
19996  66308  -19.681262  202.621592  31.471703 -0.078818 -41.499470   
19997  99637 -208.062150  218.788471  -9.157649  0.030381  -0.065924   
19998  84616  246.772616  229.348154  54.293518  0.232136  43.199142   
19999  66210  151.898254  261.236986 -85.466935  0.181286  37.720083   

               F           G          H           I  ...           K  \
0      47.178031   35.602711  -8.933317   95.386076  ...  181.354189   
1      14.509716   39.281848  -4.864431 -595.380114  ...  145.700293   
2      30.214517   66.251581  31.523355 -443.783229  ...  106.941506   
3      46.154984   32.370151  -6.535854  -85.814496  ...  145.675074   
4      28.094844   93.076054   2.500579 -643.852271  ...  127.333215   
...          ...         ...        ...         ...  ...         ...   
19995  17.399959   70.618502  -4.460998 -694.240375  ...  136.767406   
19996   9.881198   54.743271  14.100738  -74.854393  ...  153.252547   
19997  35.895902  105.127438 -84.720301 -453.066178  ...  169.877357   
19998   6.230007   89.287017   2.239845  167.285540  ...  152.720487   
19999  44.421450   73.145185 -11.386356   -2.561581  ...  105.839687   

               L          M            N            O          P           Q  \
0      -7.966671  46.040472   661.719092 -1952.914045  -5.495444  815.628857   
1      31.679372  74.035799   479.886479 -1962.005676  32.900208  752.489552   
2      40.339842  -1.463878 -1192.020689 -2045.601034  78.949252  762.424938   
3     -31.362047 -18.208619   693.586581 -1951.320671   5.432544  773.038782   
4     -19.122905  20.257857   -57.491322 -1988.874566 -14.716299  761.557824   
...          ...        ...          ...          ...        ...         ...   
19995  16.565619  -2.386540   -44.753140 -1988.237657 -41.936271  817.753509   
19996 -10.708559 -50.903469   260.286893 -1972.985655 -13.514805  801.203063   
19997  -5.008809  19.220771   488.152892 -1961.592355  21.889645  802.930133   
19998  -3.644455 -34.817907  -772.011286 -2024.600564  14.743530  779.334314   
19999  -0.466380  15.630515   198.260618 -1976.086969 -35.193154  735.736773   

               R           S           T  
0       4.880546  125.785551  800.204772  
1      30.748264  130.832421  736.119143  
2     -44.226575    7.939280  833.656738  
3     -38.283247  156.536709  768.081726  
4      27.932361 -236.948302  791.210566  
...          ...         ...         ...  
19995  41.442877  272.775392  765.619881  
19996  29.506691  -38.517142  823.359433  
19997  -5.941360  -67.821223  811.022376  
19998  67.348858  363.347336  748.942688  
19999   8.999451  -22.703220  790.467071  

[20000 rows x 21 columns]

# Parameter = ( X . XT )-1 . XT . Y



In [ ]:
def predict(parameters,xTest):  #all in numpy parameters is [[b],[w1,w2...wn]] and xTest = [1,x1,x2...xn]
  return np.dot(parameters[1] , xTest) + parameters[0][1]

def findParameters(dj, learningRate):
  w = np.zeros((1,20))
  b = 0

  numberOfIterations = 50

  for i in range(numberOfIterations):
    w = w - np.dot(learningRate , dj[0])  #dj = [[dj_dw1,...dj_dwn],[dj_db]]
    b = b - learningRate * dj[1][0]
    return [w,b]  #this returns list with 1st element an array of ws and 2nd an integer
#x = nparray[nparray1[n integers],...nparrayn[n integers]]
  #write derivative for dj functions
  def dj(x,y,parameters):
    for i in range(x.shape[1]):
      dj_dw = (1/x.shape[1])*np.dot((predict(findParameters,x[i]) - y[i]) , x)
      dj_db = (1/x.shape[1])*(predict(findParameters,x[]))

In [ ]:
parameters = [[1,2,3],[1]]
x = [3, 2, 1]

In [ ]:
predict(parameters, x)

11

# ---------------------------------------------------------------------------------------------------------------

Polynomial regression

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.linalg import inv

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/cyberlab/polynomial_train.csv')

In [ ]:
df.head(5)

Unnamed: 0            A            B           C         label
0           0 -1113.924581   952.105404 -276.045881 -1.294289e+03
1           1 -2229.480228  1111.488568  -93.454107 -2.714687e+04
2           2  2717.257713    53.431237 -179.228591  6.474300e+04
3           3 -1638.783965  -632.919447 -106.170237 -7.349871e+03
4           4  5173.934338  -721.895577  -75.074840  1.651328e+06

In [ ]:
df = df.drop(labels = "Unnamed: 0" , axis = 1)
df

A            B           C         label
0     -1113.924581   952.105404 -276.045881 -1.294289e+03
1     -2229.480228  1111.488568  -93.454107 -2.714687e+04
2      2717.257713    53.431237 -179.228591  6.474300e+04
3     -1638.783965  -632.919447 -106.170237 -7.349871e+03
4      5173.934338  -721.895577  -75.074840  1.651328e+06
...            ...          ...         ...           ...
49995  -401.109554   205.180269 -123.837422 -6.275985e+00
49996   832.536891  -723.312711 -128.736597  2.390843e+02
49997  -533.446993  1171.457335 -130.840925 -2.857080e+02
49998  1810.499103  -424.111696 -128.334986  8.161595e+03
49999  -861.910217   257.295992 -176.122871 -2.551671e+02

[50000 rows x 4 columns]

The below code breaks the dataform into training and validation set

In [ ]:
print(df.values.shape)
train = df.sample(frac=0.8, random_state = 42)
valid = df.drop(train.index)
df = train
print(df.values.shape)

(50000, 4)
(40000, 4)


In [ ]:
df

A           B           C         label
33553  1324.693049  580.869781 -112.977318  2.191858e+03
9427   2086.544457  715.837709  -97.669064  2.073085e+04
199     517.665720  556.863599 -112.573798  3.988249e+01
12447 -2009.619847  991.641267 -265.631085 -1.725527e+04
39489   369.314784  502.369374 -162.772935  1.054826e+01
...            ...         ...         ...           ...
1559  -1252.373112  583.701108  -87.565938 -1.530273e+03
13313  1020.608218 -750.737495  -28.667071  6.200909e+02
13528  -492.474749  183.781443 -241.467329 -2.028241e+01
25017   566.002871 -542.102053 -135.957452  3.672142e+01
19317 -5736.232141   38.852058  -94.316868 -2.937667e+06

[40000 rows x 4 columns]

In [ ]:
y = df["label"].values

In [ ]:
valid_y = valid["label"].values
valid_x = valid[["A" , "B" , "C"]].values

In [ ]:
y[:5]

array([ 2.19185767e+03,  2.07308500e+04,  3.98824943e+01, -1.72552747e+04,
        1.05482586e+01])

In [ ]:
A,B,C = df["A"].values,df["B"].values,df["C"].values
x = df[["A" , "B" , "C"]].values
x = np.array(x)
def predict(parameters,x):  #all in numpy parameters is [[b],[w1,w2...wn]] and xTest = [[1,x1,x2...xn],....]
    res = []
    for i in range(x.shape[0]):
      res.append(np.dot(x[i, :], parameters))

    #res = np.array(res)

    return res

def accuracy(y,yhat):
  d1 = y - yhat
  d2 = y - y.mean()
  r2 = 1 - d1.dot(d1) / d2.dot(d2)
  return r2

def addFeature(x):
  f = []
  #print(type(f))
  for i in range(x.shape[0]):
    t2 = x[i]
    t1 = np.array([A[i]*x[i][-3] , B[i]*x[i][-2] ,C[i]*x[i][-1]])
    t = np.concatenate((t2 , t1) , axis = 0)
    #print(type(f))
    f.append(t)
  f = np.array(f)
  return f

def n_eq(X, y):
    return inv(X.T.dot(X)).dot(X.T).dot(y)

def normalize(X):
    mu = X.mean(0)
    std = X.std(0)
    return (X - mu) / std, mu, std

def bias(X):
    ones = np.ones(X.shape[0]).reshape(X.shape[0], 1)
    return (np.concatenate((ones, X), 1))

x, mu, std = normalize(x)
valid_x, mu, std = normalize(valid_x)
bias(x)

acc = 0

counter = 0

while(acc<0.98 or counter <=15):
    parameters = n_eq(x, y)
    yhat = predict(parameters, valid_x)
    acc = accuracy(valid_y , yhat)
    print("acc: ", acc)
    counter+=1
    if acc<0.98 or counter <=6:
      x = addFeature(x)
      valid_x = addFeature(valid_x)


#print("acc = ",acc)


#set accuracy to minus infinity
#loop starts with degree 2
#use accuraccy function with validation set to check the accuracy
#if determined
#then increase the degree by 1



ValueError: ignored

In [ ]:
accuracy(valid_y, predict(parameters, valid_x))

-0.009832482915647978

Attempt 2

In [ ]:
df = df.drop(labels = "Unnamed: 0" , axis = 1)

print(df.values.shape)
train = df.sample(frac=0.8, random_state = 42)
valid = df.drop(train.index)
df = train
print(df.values.shape)

(50000, 4)
(40000, 4)


In [ ]:
y = df["label"].values
valid_y = valid["label"].values
valid_x = valid[["A" , "B" , "C"]].values

In [ ]:
x = df[["A" , "B" , "C"]].values
A,B,C = df["A"].values,df["B"].values,df["C"].values

In [ ]:
valid_y.shape

(10000,)

In [ ]:
valid_x.shape

(10000, 3)

# Polynomial Regression FINAL CODE

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.linalg import inv

df = pd.read_csv('/content/drive/MyDrive/cyberlab/polynomial_train.csv')
test = pd.read_csv('/content/drive/MyDrive/cyberlab/polynomial_test_data.csv')

df = df.drop(labels = "Unnamed: 0" , axis = 1)


#train = df.sample(frac=0.8, random_state = 42)
#valid = df.drop(train.index)
#df = train

y = df["label"].values
#valid_y = valid["label"].values
#valid_x = valid[["A" , "B" , "C"]].values

x = df[["A" , "B" , "C"]].values
A,B,C = df["A"].values,df["B"].values,df["C"].values

valid_x = test[["A" , "B" , "C"]].values
ids = test[["ids"]].values

def predict(parameters,x):
    res = []
    for i in range(x.shape[0]):
      res.append(np.dot(x[i], parameters))

    return res

def accuracy(y,yhat):
  d1 = y - yhat
  d2 = y - y.mean()
  r2 = 1 - d1.dot(d1) / d2.dot(d2)
  return r2

def n_eq(X, y):
    return inv(X.T.dot(X)).dot(X.T).dot(y)

def normalize(X):
    mu = X.mean(0)
    std = X.std(0)
    return (X - mu) / std, mu, std

def bias(X):
    ones = np.ones(X.shape[0]).reshape(X.shape[0], 1)
    return (np.concatenate((ones, X), 1))


A2 = np.multiply(x[:, 0], x[:, 0])
a2 = np.multiply(valid_x[:, 0], valid_x[:, 0])
x = np.concatenate((x, A2.reshape((x.shape[0],1))), axis = 1)
valid_x = np.concatenate((valid_x, a2.reshape((valid_x.shape[0],1))), axis = 1)


AB = np.multiply(x[:, 0], x[:, 1])
ab = np.multiply(valid_x[:, 0], valid_x[:, 1])
x = np.concatenate((x, AB.reshape((x.shape[0],1))), axis = 1)
valid_x = np.concatenate((valid_x, ab.reshape((valid_x.shape[0],1))), axis = 1)

AC = np.multiply(x[:, 0], x[:, 2])
ac = np.multiply(valid_x[:, 0], valid_x[:, 2])
x = np.concatenate((x, AC.reshape((x.shape[0],1))), axis = 1)
valid_x = np.concatenate((valid_x, ac.reshape((valid_x.shape[0],1))), axis = 1)


A3 = np.multiply(x[:, 0], x[:, 3])
a3 = np.multiply(valid_x[:, 0], valid_x[:, 3])
x = np.concatenate((x, A3.reshape((x.shape[0],1))), axis = 1)
valid_x = np.concatenate((valid_x, a3.reshape((valid_x.shape[0],1))), axis = 1)



#x,m,s = normalize(x)
#valid_x,h,j = normalize(valid_x)
x = bias(x)
valid_x = bias(valid_x)

parameters = n_eq(x, y)

res = predict(parameters, valid_x)
res = np.array(res)
res = res.reshape(res.shape[0], 1)
output = np.concatenate((ids, res), 1)
res1 = res.T[0]
ids1 = ids.T[0]

outputDict = {
    'Ids': list(ids1),
    'Result': list(res1)
}

outputDictdf = pd.DataFrame(outputDict)

outputDictdf.to_csv("PolynomialRegressionOutputPandas.csv")
#acc = accuracy(valid_y, yhat)
#print("Acc : {:.3f} %".format(acc*100))

In [ ]:
np.savetxt('polynomialOutput.csv', output, delimiter= ',')

array([[ 1.00000000e+00,  1.32469305e+03,  5.80869781e+02,
        -1.12977318e+02,  1.75481168e+06],
       [ 1.00000000e+00,  2.08654446e+03,  7.15837709e+02,
        -9.76690638e+01,  4.35366777e+06],
       [ 1.00000000e+00,  5.17665720e+02,  5.56863599e+02,
        -1.12573798e+02,  2.67977797e+05],
       ...,
       [ 1.00000000e+00, -4.92474749e+02,  1.83781443e+02,
        -2.41467329e+02,  2.42531378e+05],
       [ 1.00000000e+00,  5.66002871e+02, -5.42102053e+02,
        -1.35957452e+02,  3.20359250e+05],
       [ 1.00000000e+00, -5.73623214e+03,  3.88520582e+01,
        -9.43168679e+01,  3.29043592e+07]])

In [ ]:
def addFeature(x, l):
  f = list(x)
  for i in l:
    for j in range(len(f)):
      f[j].append((f[j][0]**int(i[0]))*(f[j][1]**int(i[1]))*(f[j][2]**int(i[2])))
  return np.array(f)

In [ ]:
addFeature([[1,2,3]], ["200", "031"])

array([[ 1,  2,  3,  1, 24]])

In [ ]:
xtest = np.array([[1,2,3,4,5] , [4,5,6,7,8] , [0,0,1,2,3]])



In [ ]:
temp = np.multiply(xtest[:, 0], xtest[:, 1])

In [ ]:
xtest,temp

(array([[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8],
        [0, 0, 1, 2, 3]]), array([ 2, 20,  0]))

In [ ]:
np.concatenate((xtest, temp.reshape((xtest.shape[0],1))), axis = 1)

array([[ 1,  2,  3,  4,  5,  2],
       [ 4,  5,  6,  7,  8, 20],
       [ 0,  0,  1,  2,  3,  0]])